---
services:
  speedtest-exporter:
    image: ghcr.io/miutaku/speedtest-exporter:latest
    container_name: speedtest-exporter
    ports:
      - 8080:8080
    restart: always
#  node-exporter:
#    image: prom/node-exporter:latest
#    container_name: node-exporter
#    ports:
#      - 9100:9100
#    command:
#      - '--path.rootfs=/host'
#    pid: host
#    restart: unless-stopped
#    volumes:
#      - '/:/host:ro,rslave'
