---
name: docker build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: create meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.actor }}/speedtest-exporter
          tags: |
            type=raw,value=latest
            type=sha,prefix=,suffix=,format=short

      - name: Build container image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          push: false
          platforms: linux/amd64,linux/arm64
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: create meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.actor }}/speedtest-exporter
          tags: |
            type=raw,value=latest
            type=sha,prefix=,suffix=,format=short

      - name: Push container image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
